# CI process 

name: CI_for_ser_fd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world from testing!
        
          
  my_deploy:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Run a one-line script
        run: echo Hello, world from deploy! 
