# CI process 

name: CI_for_ser_fd

env:
  APPLICATION_NAME : "server_fd"
  PACKAGE_NAME     : "deploy-ver-${{ github.sha }}"
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world from testing! 
        
      - name: Execute few commands
        run: |
          echo "Hellow Message1"
          echo "Hellow Message1"
          echo "Aplication name is ${{ env.APPLICATION_NAME}}"
          
      - name: List curent folder
        run: ls -la
          
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List curent folder
        run: ls -la 
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env: 
      VAR: "var1"     
    
    steps: 
      - name: Run a one-line script
        run: echo Hello, world from deploy ${{ env.VAR1 }}! 
        
      - name: Execute few commands
        run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
        
      - name: Lets test some packages if they are here
        run: aws --version
